spring:
  application:
    name: SHIFT_Lab_Java_May_2026

  datasource:
    url: jdbc:postgresql://localhost:5432/shift_postgres
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true